// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Needs } from "./Needs";

/**
 * Per-agent snapshot row. Holds the slice of state this pass exposes;
 * other groupings (Personality, Mood, Spatial, …) extend this type as
 * their first consumer system lands.
 */
export type AgentSnapshot = { id: AgentId, name: string, needs: Needs, };
