// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { CurrentActionView } from "./CurrentActionView";
import type { LeafAreaId } from "./LeafAreaId";
import type { Mood } from "./Mood";
import type { Needs } from "./Needs";
import type { Personality } from "./Personality";
import type { Phase } from "./Phase";
import type { Vec2 } from "./Vec2";

/**
 * Per-agent snapshot row. Holds the slice of state this pass exposes;
 * other groupings (Memory, Skills, …) extend this type as their first
 * consumer system lands.
 */
export type AgentSnapshot = { id: AgentId, name: string, needs: Needs, mood: Mood, personality: Personality, leaf: LeafAreaId, pos: Vec2, facing: Vec2, action_phase: Phase | null, current_action: CurrentActionView | null, };
