// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingId } from "./BuildingId";
import type { DistrictId } from "./DistrictId";
import type { Rect2 } from "./Rect2";

export type Building = { id: BuildingId, display_name: string, district: DistrictId, footprint: Rect2, };
