// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerInput } from "./PlayerInput";

/**
 * Client-originated frame. Tagged with `"type"` field (`snake_case`).
 */
export type ClientMessage = { "type": "client_hello", last_known_tick: number | null, } | { "type": "player_input" } & PlayerInput;
