// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lossy projection of `CommittedAction` for the wire. Carries enough for
 * the frontend to render "Alice is doing X (50%)". The full
 * `CommittedAction` lives only as an ECS component.
 */
export type CurrentActionView = { 
/**
 * `Advertisement.display_name` for object-targeted actions, or
 * `"Idle"` / `"Wait"` for self-actions.
 */
display_name: string, 
/**
 * Progress through the action's `perform_duration_ticks`. `0.0`
 * while `Walking`; rises monotonically toward `1.0` while
 * `Performing`.
 */
fraction_complete: number, };
