// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectId } from "./ObjectId";
import type { Phase } from "./Phase";
import type { Vec2 } from "./Vec2";

/**
 * Lossy projection of `CommittedAction` for the wire. Carries enough for
 * the frontend to render "Alice is doing X (50%)". The full
 * `CommittedAction` lives only as an ECS component.
 */
export type CurrentActionView = { 
/**
 * `Advertisement.display_name` for object-targeted actions, or
 * `"Idle"` / `"Wait"` for self-actions.
 */
display_name: string, 
/**
 * Progress through the action's `perform_duration_ticks`. `0.0`
 * while `Walking`; rises monotonically toward `1.0` while
 * `Performing`.
 */
fraction_complete: number, 
/**
 * Current phase of the committed action.
 */
phase: Phase, 
/**
 * Target object id for object-targeted actions.
 */
target_object_id: ObjectId | null, 
/**
 * Committed interaction position for the current action.
 */
target_position: Vec2 | null, 
/**
 * Human-readable target label when one is known.
 */
target_label: string | null, };
