// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DistrictId } from "./DistrictId";
import type { Rect2 } from "./Rect2";

export type District = { id: DistrictId, display_name: string, bbox: Rect2, };
