// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec2 } from "./Vec2";

/**
 * Unit direction the agent is oriented. Updated by the movement system
 * during walking; mood / social systems may also nudge this without
 * moving the agent — kept as its own component so writes don't
 * conflict with `Position` writers.
 */
export type Facing = { dir: Vec2, };
