// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingId } from "./BuildingId";
import type { FloorId } from "./FloorId";

export type Floor = { id: FloorId, building: BuildingId, 
/**
 * Ground floor = 0; basement levels negative. Per ADR 0007.
 */
level: number, };
