// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeafAreaId } from "./LeafAreaId";
import type { LeafKind } from "./LeafKind";
import type { Rect2 } from "./Rect2";

/**
 * A leaf area: room or outdoor zone. Per ADR 0007 these are the only
 * places agents and smart objects actually live; everything else
 * (district / building / floor) is a containment shell.
 */
export type LeafArea = { id: LeafAreaId, display_name: string, kind: LeafKind, bbox: Rect2, 
/**
 * Other leaf areas reachable in one step. Symmetric in
 * `WorldGraph::seed_v0`; later content loaders should validate.
 */
adjacency: Array<LeafAreaId>, };
