// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildingId } from "./BuildingId";
import type { FloorId } from "./FloorId";
import type { OutdoorZoneKind } from "./OutdoorZoneKind";

/**
 * What sits inside a leaf area — either a room of a specific floor in a
 * specific building, or an outdoor zone of a given kind. Per ADR 0007.
 */
export type LeafKind = { "Room": { building: BuildingId, floor: FloorId, } } | { "OutdoorZone": OutdoorZoneKind };
