// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Short-term emotional state per ADR 0011 (3-dimensional vector).
 * Doubles as the ECS component (lazy sharding — schema and component
 * share a type until a future pass needs them to diverge).
 */
export type Mood = { 
/**
 * In `[-1, 1]`. Negative = unhappy, positive = happy.
 */
valence: number, 
/**
 * In `[0, 1]`. 0 = calm, 1 = alert / excited.
 */
arousal: number, 
/**
 * In `[0, 1]`. 0 = none, 1 = max stress.
 */
stress: number, };
