// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All six need values, each in `[0, 1]`. Per ADR 0011. Doubles as the
 * ECS component for needs (lazy sharding — schema and component share a
 * type until a future pass needs them to diverge).
 */
export type Needs = { hunger: number, sleep: number, social: number, hygiene: number, fun: number, comfort: number, };
