// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeafAreaId } from "./LeafAreaId";
import type { ObjectId } from "./ObjectId";
import type { ObjectTypeId } from "./ObjectTypeId";
import type { Vec2 } from "./Vec2";

/**
 * Per-instance smart-object row sent every snapshot. Carries the data
 * the renderer needs to draw the object: id, type (for mesh lookup),
 * leaf area, world-space position. Per-instance dynamic state
 * (e.g. fridge open/closed) is deferred until any object actually has
 * visible state — see the spatial-pass spec's deferred items.
 */
export type ObjectSnapshot = { id: ObjectId, type_id: ObjectTypeId, leaf: LeafAreaId, pos: Vec2, };
