// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Big Five personality components; each in `[-1, 1]`. Per ADR 0011.
 * Doubles as the ECS component (lazy sharding). Sampled at agent spawn
 * via `Personality::sample(rng)`; `Default` is retained for unit tests
 * that build hand-crafted worlds and want zero personality.
 */
export type Personality = { openness: number, conscientiousness: number, extraversion: number, agreeableness: number, neuroticism: number, };
