// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Driver-bound player inputs. Tagged with `"kind"` so the outer
 * `ClientMessage` "type" tag stays unique.
 */
export type PlayerInput = { "kind": "set_speed", multiplier: number, } | { "kind": "toggle_pause" };
