// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LeafAreaId } from "./LeafAreaId";
import type { Vec2 } from "./Vec2";

/**
 * Where an agent currently is. `leaf` and `pos` update together — an
 * agent crosses a leaf boundary by changing both fields at once. Per
 * ADR 0007: `pos` is continuous f32 within the leaf area; the 0.5m
 * grid mentioned in the ADR is enforced only at smart-object placement,
 * not on agent positions.
 */
export type Position = { leaf: LeafAreaId, pos: Vec2, };
