// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vec2 } from "./Vec2";

/**
 * Axis-aligned 2D bounding box in meters. ADR 0007 leaf-area / building
 * / district footprint shape.
 */
export type Rect2 = { min: Vec2, max: Vec2, };
