// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snapshot } from "./Snapshot";
import type { WireFormat } from "./WireFormat";

/**
 * Server-originated frame. Tagged with `"type"` field (`snake_case`).
 */
export type ServerMessage = { "type": "hello", protocol_version: number, format: WireFormat, } | { "type": "init", current_tick: bigint, snapshot: Snapshot, } | { "type": "snapshot", snapshot: Snapshot, };
