// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSnapshot } from "./AgentSnapshot";

/**
 * Full sim state at a tick boundary. `PartialEq` is required by the
 * determinism test in the test suite; serde derives let `protocol`
 * envelope this type without a parallel wire shape.
 */
export type Snapshot = { tick: bigint, agents: Array<AgentSnapshot>, };
