// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 2D vector / point in meters. Wire-friendly `{ x, y }` shape so JSON
 * inspection and TypeScript consumption read naturally. Replaces the
 * former `pub use glam::Vec2;` re-export — `glam` is no longer a runtime
 * dependency of the schema.
 */
export type Vec2 = { x: number, y: number, };
