// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire encoding negotiated in `Hello.format`. Json-only for v0; the
 * extra variant slot anchors future `MessagePack` / postcard support.
 */
export type WireFormat = "json";
