// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Building } from "./Building";
import type { District } from "./District";
import type { Floor } from "./Floor";
import type { LeafArea } from "./LeafArea";
import type { LeafAreaId } from "./LeafAreaId";

/**
 * One-shot world layout payload for the renderer. Wraps the
 * `WorldGraph` in deterministic, sorted vectors so JSON round-trip is
 * byte-stable for a given graph.
 */
export type WorldLayout = { districts: Array<District>, buildings: Array<Building>, floors: Array<Floor>, leaves: Array<LeafArea>, default_spawn_leaf: LeafAreaId, };
